// Authentication Action Types
export const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const LOGGED_OUT_SUCCESS = "LOGGED_OUT_SUCCESS";
export const LOG_OUT_ERROR = "LOG_OUT_ERROR";

// Actions for fetching editions
export const FETCH_EDITIONS = "FETCH_EDITIONS";
export const FETCHED_EDITIONS_SUCCESS = "FETCHED_EDITIONS_SUCCESS"
export const FETCHED_EDITIONS_ERROR = "FETCHED_EDITIONS_ERROR";
export const CLEAR_FETCHED_EDITIONS_ERROR = "CLEAR_FETCHED_EDITIONS_ERROR";

// Actions for creating editions
export const CREATED_EDITION_SUCCESS = "CREATED_EDITION_SUCCESS";
export const CREATED_EDITION_ERROR = "CREATED_EDITION_ERROR";
export const CLEAR_CREATED_EDITION_ERROR = "CLEAR_CREATED_EDITION_ERROR";

export const DELETED_EDITION_SUCCESS = "DELETED_EDITION_SUCCESS";
export const DELETED_EDITION_ERROR = "DELETED_EDITION_ERROR";

// Actions for viewing/switching between editions
export const SELECT_EDITION = "SELECT_EDITION";